import Head from 'next/head';
import Home from '../components/Home';

export default function Index(props) {
  const title = "TERA";
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Home title={title} isSSR={props.isSSR} />
    </>
  )
}

export async function getServerSideProps() {
  return { props: { isSSR: true } }
}
