import Head from 'next/head';
import Image from 'next/image';
import ConsultarCnab from '../components/ConsultarCnab';
import styles from '../styles/Home.module.css';

export default function Home() {
  const title = "TERA";
  const navbar = `navbar navbar-expand-lg navbar-dark ${styles.navbar}`;
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <nav className={navbar}>
        <div className="container-fluid">
          <a className="navbar-brand d-flex" href="#">
            <Image src="/img/logo-tera-b.png" alt="Logo Tera" width={30} height={30} className="d-inline-block align-text-top" />
            <span className="ms-2">{title}</span>
          </a>

          {/* <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span className="navbar-toggler-icon"></span>
          </button>
          <div className="collapse navbar-collapse" id="navbarSupportedContent">
            <ul className="navbar-nav me-auto mb-2 mb-lg-0"></ul>
          </div> */}
        </div>
      </nav>

      <main className="container-fluid mt-3">
        <ConsultarCnab />
      </main>
    </div>
  )
}
